{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helmchart-for-vaas.serviceAccountName" . }}
  namespace: {{ include "helmchart-for-vaas.namespace" . }}
  labels:
    {{- include "helmchart-for-vaas.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}