{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmchart-for-vaas.fullname" . }}
  namespace: {{ include "helmchart-for-vaas.namespace" . }}
  labels:
    {{- include "helmchart-for-vaas.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helmchart-for-vaas.selectorLabels" . | nindent 4 }}
{{- end }}    